"""Add group to ComponentCategory

Revision ID: 262914f1a34d
Revises: 6913d32a72fa
Create Date: 2026-08-24 19:20:38.531911

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '262914f1a34d'
down_revision: Union[str, Sequence[str], None] = '6913d32a72fa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('component_categories', sa.Column('group', sa.String(), nullable=True))
    op.create_index(op.f('ix_component_categories_group'), 'component_categories', ['group'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_component_categories_group'), table_name='component_categories')
    op.drop_column('component_categories', 'group')
    # ### end Alembic commands ###
